nathanbabcock/ffmpeg-sidecar

- examples/h265_transcode.rs
- src/event.rs
- src/iter.rs
- src/log_parser.rs
This PR adds a separate parsing of fatal error logs so that they can be handled separately. I initially did this by adding a `FfmpegEvent::LogFatal` but in the last commit I changed this to make it a single `FfmpegEvent::Log` with a `LogLevel` field. I don't have a strong opinion in either direction so I'll leave the decision up to you.
I also changed the log parsing logic  to check if a log line contains the log level in square braces (instead of starting with it) because I encountered a few logs like this that would otherwise be parsed incorrectly:
```
[swscaler @ 000001ceadc00b80] [swscaler @ 000001ceadd3b7c0] [warning] deprecated pixel format 
used, make sure you did set range correctly
```
I didn't add tests because there currently aren't any for the `parse_next_event` function and I …
> Add separate parsing of fatal logs

- src/command.rs
This adds a convenience function to disable creating a new console window for every spawned ffmpeg process when running on Windows. This is especially useful when you use this library for a GUI program where you don't want to open a bunch of empty console widows.
> Add option to not create console window when spawning ffmpeg on Windows

- src/command.rs
I noticed during debugging that the current implementation doesn't produce an output that can be copy-pasted and run so here's a quick fix for that.
> Fix the print_command() method to print an easily copyable command

- examples/h265_transcode.rs
- src/child.rs
- src/download.rs
- src/event.rs
- src/iter.rs
- src/log_parser.rs
- src/read_until_any.rs
- src/test.rs
Closes #10 
- Rewrite metadata collection to avoid an inner loop inside the constructor
- On certain errors execution could block inside this inner loop, never yielding items to the Iterator
- Collect metadata into a single struct
- Add `collect_metadata` method to advance iterator past metadata section and return the finalized metadata
- Recognize audio streams and other stream types, though no parsing of their contents yet
> Improve Iterator metadata collection

- examples/trigger.rs
- src/download.rs
- src/event.rs
- src/iter.rs
- src/lib.rs
- src/log_parser.rs
- src/metadata.rs
- src/test.rs
- src/version.rs
- Determine expected output duration from metadata
- Parse FFmpeg time/duration strings with `parse_time_str`
- Improve error handling in `collect_metadata` to "bubble up" errors from inside the iterator
> Duration metadata

- src/child.rs
- src/command.rs
Every call to `spawn` without a call on the Result to `wait` results in a zombie process that stays until the main thread exits. This lead to OS issues with large datasets because it is possible that all PID's are used by the zombies.
This PR exposes the `wait` method of `std::process::Child` to the user, giving the possibility to wait for the process to complete and clean up properly.
It has only been tested on Linux.
I am happy to further adjust the code to your coding/documentation style requirements.
Best regards,
Lewin
> feat: Added wait method on FfmpegChild

- src/test.rs
A simple test to ensure the name of the filter argument is applied correctly; covers the bug fixed in #27.
> Add unit test to cover `filter_complex`

- README.md
Fixes https://github.com/nathanbabcock/ffmpeg-sidecar/issues/29
> Make README.md example same as /examples/ one

- src/command.rs
This is tiny pr that adds two new functions for `FfmpegCommand`: to control `crf` and `preset` of output media
> Add two new options for video-options

- src/log_parser.rs
Closes #31 
Before (6.0 and earlier):
```
[info] frame= 1996 fps=1984 q=-1.0 Lsize=     372kB time=00:01:19.72 bitrate=  38.2kbits/s speed=79.2x\n
```
After (7.0 onwards):
```
[info] frame=    5 fps=0.0 q=-1.0 Lsize=      10KiB time=00:00:03.00 bitrate=  27.2kbits/s speed= 283x\n
```
**TL;DR:** `kB` changed to `KiB` 😅
> Fix for FFmpeg v7: "KiB" filesize units in progress updates

- .github/workflows/mac-m1.yml
- .github/workflows/mac.yml
- .github/workflows/ubuntu.yml
- examples/download_ffmpeg.rs
- src/download.rs
- src/test.rs
> update macos runners

- examples/h265_transcode.rs
- src/command.rs
- src/test.rs
Intended fix is to append `-n` to any command which doesn't otherwise specify how to handle overwrites. It's backwards compatible as it only addresses the bugged case where the process is hung waiting for interactive input.
Fixes #35
> fix: prevent hang waiting for stdin on overwrite prompt

- src/command.rs
- src/download.rs
- src/ffprobe.rs
- src/log_parser.rs
- src/version.rs
Fixes #40 
- The user can still override this before `spawn()` by using the `CommandExt::creation_flags` method directly
- Provides an internal extension trait on all `Command`'s that conditionally applies the right creation flags only on Windows
- Apply that method on every `Command` used in the library, including `curl()`, `unpack_ffmpeg()`, `ffmpeg_version()`, etc
> fix: apply windows creation flags to all command subprocesses

- Cargo.toml
- src/download.rs
**Steps I have taken:**
- Used the reqwest blocking feature to download files .
**Potential Concerns:**
- Currently, the ffmpeg is not downloaded using streaming
- To stream download the file, I think we have to create async download function. ( I personally didn't wanted to go for the async thing, becauase the whole library is not using async )
- For the download progress feature, we need to stream download the file, which is not done in this PR.
**Personal Feelings ( My Personal Opinion only )**
- I think the download progress feature should not be a part of this library, just feels it is out of scope of this library's utility, users can implement their own download progress feature or use another library for it .
Maintainer, feel free to suggest different approach ..
> Removed curl dependency with reqwest

- README.md
- examples/hello_world.rs
- src/event.rs
- src/iter.rs
- src/lib.rs
- src/log_parser.rs
- src/metadata.rs
- src/pix_fmt.rs
* Refactor code into common processing for all streams and spezialized functions for audio and video.
* Update code examples
* Change line breaks in lib.rs to LF
* Add handling of streams that contain additional identifiers in square
brackets such as `Stream #0:1[0x2](eng):`. These are found in mov
containers.
Partly discussed in https://github.com/nathanbabcock/ffmpeg-sidecar/issues/49
> feat!: Add audio and subtitle stream parsing

- src/command.rs
It exists for audio and video but not for subtitle.
> feat: Add option alias for subtitle codec

- src/download.rs
Removes the functions deprecated in v1.2 (#48) in preparation for major version bump
> chore: remove deprecated curl functions

- .github/workflows/mac.yml
- .github/workflows/ubuntu.yml
- src/download.rs
Currently compilation fails when building for non-linux without the `download_ffmpeg` feature.
This happens because the `zip` library is (correctly) feature gated to `download_ffmpeg`. This in turn is used by `unpack_ffmpeg` which wasn't behind the feature flag!
> Fix non-default feature build: Feature gate `unpack_ffmpeg` with `download_ffmpeg`

- Cargo.toml
- examples/named_pipes.rs
- examples/sockets.rs
- rust-toolchain
- src/command.rs
Having a set MSRV is a good idea, as is enforcing it with a `rust-toolchain` file.
We can probably use an earlier version if you prefer; i just went with 1.79 for no particular reason. Let me know!
> Add `rust-toolchain` and set MSRV to 1.79

- src/iter.rs
- src/pix_fmt.rs
Two separate fixes actually:
* `get_bytes_per_frame` assumed that a bits per pixel size that is not divisible by 8 means that it can't retrieve the frame size because that will yield a frame buffer with a non full-byte size. This is not _entirely_ true since for instance YUV formats typically have size restrictions such that their raw frame buffers don't run into this problem. ➡️ The check got changed to the frame buffer's size
* don't panic when `get_bytes_per_frame` can't return a size and instead report the error and exit 
The former fixes using yuv formats for me, the later is a bit of a general requirement for me since I deal with arbitrary user data: not being able to handle data is sad, but crashing over it goes too far :)
> Fix crash when using formats with bits per pixel size not divisible by 8

- src/command.rs
- src/iter.rs
- src/test.rs
This PR revamps `spawn_stdout_thread` to make the following behavior more explicit and clear:
Also adds some unit tests, including coverage for the bug fixed by #61
> fix: fall back to chunked mode for unknown frame buffer sizes

- src/log_parser.rs
> fix: handle non-utf8 bytes in log parser

- src/child.rs
- src/test.rs
Fixes #70 
The stderr channel of the FFmpeg process is configured with `Stdio::piped()` by default, which is used to parse log messages for the iterator. However, this can cause problems when used with `FfmpegChild.wait()`. Log messages will continue to fill up that piped stdio channel without ever being consumed. If there aren't too many log messages, the command will finish successfully. There's enough room for several hundred log lines, which is why this bug never surfaced before. However, once the whole buffer is filled, then FFmpeg will hang while it waits for more room to insert log messages (which continues indefinitely).
The solution is to automatically ~~drop~~ consume the piped stderr channel when `wait()` is called.
> fix: consume stderr on wait

- .github/workflows/windows.yml
this is the same logic I do with my async fork. The reason timeout is at 10 minutes is for some reason it is a lot slower compared to linux and m1 runners
partly addresses #60
> add windows ci

- src/log_parser.rs
This can occur when outputting to multiple files (i.e. when exporting frames to individual image files).
> fix: Handle `"N/A"` size progress properly

- src/event.rs
- src/log_parser.rs
TL;DR: audio events will have `0` for unsupported fields. Fixes #81 
---
This is a quick non-breaking fix, supporting parsing audio progress messages which have a slightly different format than video ones:
**Video progress:**
```
[info] frame= 1996 fps=1984 q=-1.0 Lsize=     372kB time=00:01:19.72 bitrate=  38.2kbits/s speed=79.2x
```
**Audio progress:**
```txt
[info] size=      66kB time=00:00:02.21 bitrate= 245.0kbits/s speed=1.07x
```
Specifically audio progress omits `frame`, `fps`, and `q` fields.
The most thorough and typesafe fix will be to add a dedicated `AudioProgress` event type with those fields omitted. That would be a breaking change in conjunction with adding `#[non_exhaustive]` to support future added event types.
cc @ashhhleyyy fyi
> emit audio progress events

- .github/workflows/ci.yml
- Replace `macos-13` runner with `macos-15-intel`
> Switch off of deprecated `macos-13` Github Actions runner
